name: location-privacy-lab
region: tor

services:
  - name: api
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /api
    health_check:
      http_path: /health

  - name: frontend
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    build_command: ""
    envs:
      - key: VITE_API_URL
        value: ${api.PUBLIC_URL}/api
        type: BUILD_TIME
      - key: VITE_MAPBOX_TOKEN
        value: ""
        type: BUILD_TIME
    routes:
      - path: /
