name: lt-privacy
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: Benedict-Kpaduwa/Location-Privacy
    http_port: 10000
    instance_count: 1
    instance_size_slug: basic-xxs
    dockerfile_path: Dockerfile
    envs:
      - key: VITE_API_URL
        value: /api
        scope: RUN_AND_BUILD_TIME
      - key: VITE_MAPBOX_TOKEN
        value: "" # User should set this in DO dashboard
        scope: RUN_AND_BUILD_TIME
